Update vm-deployment.yml

diff --git a/.github/workflows/vm-deployment.yml b/.github/workflows/vm-deployment.yml
--- a/.github/workflows/vm-deployment.yml
+++ b/.github/workflows/vm-deployment.yml
@@ -1,12 +1,15 @@
 name: Deploy to AWS Docker on merge to prod
+
 on:
   push:
     branches:
       - prod
+  workflow_dispatch: # Enables manual triggering
 
 jobs:
   docker:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -34,7 +37,7 @@ jobs:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
-      - name: Build and Push
+      - name: Build and Push Docker Image
         uses: docker/build-push-action@v6
         with:
           context: .
@@ -52,7 +55,7 @@ jobs:
           target: "/home/ubuntu/backend"
           overwrite: true
 
-      - name: Docker Compose
+      - name: Deploy with Docker Compose
         uses: appleboy/ssh-action@v1.0.3
         with:
           host: ${{ secrets.HOST_SERVER }}
@@ -60,10 +63,11 @@ jobs:
           key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
           port: 22
           script: |
+            set -e # Stop execution on error
             cd /home/ubuntu/backend
             mv docker-compose-prod.yml docker-compose.yml
-            echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
-            docker compose down
+            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
+            docker compose down || true # Ignore if not running
             docker compose pull
             docker compose up -d
             # Optional cleanup
